import NextHead from 'next/head';

const Head = () => (
    <NextHead>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta
            name='keywords'
            content='Pod Smerkami, Szklarska Poręba, domki, pokoje, nocleg, hotel, pensjonat, b2b, apartamenty, booking, nocowanie, kontakt, opinie, domek, menu'
        />
        <meta name='robots' content='index, follow' />
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
        <meta http-equiv='content-language' content='pl-PL' />
        <meta name='author' content='Pod Smerkami Szklarska Poręba' />
        <meta name='DC.title' content='Pod Smerkami' />
        <meta name='geo.region' content='PL-DS' />
        <meta name='geo.placename' content='Szklarska Poręba' />
        <meta name='geo.position' content='50.836326;15.508455' />
        <meta name='ICBM' content='50.836326, 15.508455' />

        {/* Open Graph / Facebook */}
        <meta property='og:type' content='website' />
        <meta property='og:url' content='https://podsmerkami.pl' />
        <meta property='og:title' content='Pod Smerkami - Szklarska Poręba | Domki, Pokoje, Nocleg, Kontakt' />
        <meta
            property='og:description'
            content='Spotkajmy się w Pod Smerkami - Szklarska Poręba. W naszej ofercie znajdziesz domki, pokoje, nocleg, liczne atrakcje i wiele więcej.'
        />
        <meta property='og:image' content='https://t-cf.bstatic.com/images/hotel/max1280x900/164/164962944.jpg' />

        {/* Twitter */}
        <meta property='twitter:card' content='summary_large_image' />
        <meta property='twitter:url' content='https://podsmerkami.pl' />
        <meta property='twitter:title' content='Pod Smerkami - Szklarska Poręba | Domki, Pokoje, Nocleg, Kontakt' />
        <meta
            property='twitter:description'
            content='Spotkajmy się w Pod Smerkami - Szklarska Poręba. W naszej ofercie znajdziesz domki, pokoje, nocleg, liczne atrakcje i wiele więcej.'
        />
        <meta property='twitter:image' content='https://t-cf.bstatic.com/images/hotel/max1280x900/164/164962944.jpg' />

        {/* Structure Data */}
        <script type='application/ld+json'>
            {`{
                        "@context": "https://schema.org",
                        "@type": "BedAndBreakfast",
                        "name": "Pod Smerkami - Szklarska Poręba",
                        "image": "https://t-cf.bstatic.com/images/hotel/max1280x900/164/164962944.jpg",
                        "@id": "PodSmerkamiSzklarskaPoręba",
                        "url": "https://podsmerkami.pl",
                        "telephone": "+48501026529",
                        "priceRange": "$",
                        "smokingAllowed": "false",
                        "petsAllowed": "true",
                        "review": {
                            "@type": "Review",
                            "reviewRating": {
                                 "@type": "Rating",
                                "ratingValue": "4.5",
                                "bestRating": "5"
                            },
							"author": {
								"name": "Jan Kowalski"
							}
                        },
                        "address": {
                            "@type": "PostalAddress",
                            "streetAddress": "Słowackiego 17",
                            "addressLocality": "Szklarska Poręba",
                            "postalCode": "58-580",
                            "addressCountry": "PL"
                        },
                        "geo": {
                            "@type": "GeoCoordinates",
                            "latitude": 50.8362516,
                            "longitude": 15.5084861
                        },
                        "openingHoursSpecification": {
                            "@type": "OpeningHoursSpecification",
                            "dayOfWeek": [
                            "Monday",
                            "Tuesday",
                            "Wednesday",
                            "Thursday",
                            "Friday",
                            "Saturday",
                            "Sunday"
                            ],
                            "opens": "00:00",
                            "closes": "23:59"
                        },
                        "sameAs": [
                            "https://www.facebook.com/PodSmerkami",
                            "https://podsmerkami.pl"
                        ]
                        }`}
        </script>

        {/* Other */}
        <link rel='apple-touch-icon' sizes='57x57' href='/icons/apple-icon-57x57.png' />
        <link rel='apple-touch-icon' sizes='60x60' href='/icons/apple-icon-60x60.png' />
        <link rel='apple-touch-icon' sizes='72x72' href='/icons/apple-icon-72x72.png' />
        <link rel='apple-touch-icon' sizes='76x76' href='/icons/apple-icon-76x76.png' />
        <link rel='apple-touch-icon' sizes='114x114' href='/icons/apple-icon-114x114.png' />
        <link rel='apple-touch-icon' sizes='120x120' href='/icons/apple-icon-120x120.png' />
        <link rel='apple-touch-icon' sizes='144x144' href='/icons/apple-icon-144x144.png' />
        <link rel='apple-touch-icon' sizes='152x152' href='/icons/apple-icon-152x152.png' />
        <link rel='apple-touch-icon' sizes='180x180' href='/icons/apple-icon-180x180.png' />
        <link rel='icon' type='image/png' sizes='192x192' href='/icons/android-icon-192x192.png' />
        <link rel='icon' type='image/png' sizes='32x32' href='/icons/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='96x96' href='/icons/favicon-96x96.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='/icons/favicon-16x16.png' />
        <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />
        <meta name='msapplication-TileImage' content='/icons/ms-icon-144x144.png' />
        <meta name='msapplication-TileColor' content='#ffffff' />
        <meta name='theme-color' content='#ffffff' />
        <link rel='manifest' href='/manifest.json' />
        <link rel='canonical' href='https://podsmerkami.pl' />

        {/* Bootstrap */}
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' rel='stylesheet' />
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js' />
    </NextHead>
);

export default Head;
